import * as THREE from 'three';
import type { SurfaceKind } from '../../contracts/types';

export interface SurfaceTextures {
  map: THREE.Texture;
  normal: THREE.Texture;
  rough: THREE.Texture;
  /** world meters covered by one texture repeat */
  tileSize: number;
  normalStrength: number;
  roughMin: number;
  roughMax: number;
  /** linear albedo multiplier (keeps the authored maps, corrects overall value/hue under the studio light) */
  tint: [number, number, number];
  dispose(): void;
}

/** Self-authored texture sets in public/textures (generated by scripts/textures/make_floors.py). */
export const SURFACES: Record<SurfaceKind, { tileSize: number; normalStrength: number; roughMin: number; roughMax: number; tint: [number, number, number]; fallback: string }> = {
  // Normal maps are authored with physical slopes (heights in mm) and encoded green-down to match
  // Floor.ts' tangent frame (T = +X, B = -Z); see scripts/textures/make_floors.py.
  // oak maps average linear (0.66, 0.46, 0.27): far too light and orange for a natural light oak (~0.45/0.33/0.21)
  oak: { tileSize: 1.6, normalStrength: 1.0, roughMin: 0.36, roughMax: 0.72, tint: [0.7, 0.72, 0.8], fallback: '#d4b58d' },
  stone: { tileSize: 1.2, normalStrength: 1.0, roughMin: 0.4, roughMax: 0.75, tint: [0.84, 0.84, 0.85], fallback: '#cecac1' },
  carpet: { tileSize: 0.5, normalStrength: 1.0, roughMin: 0.82, roughMax: 1.0, tint: [1, 1, 1], fallback: '#a39b90' },
};

const loader = new THREE.TextureLoader();

function load(url: string, srgb: boolean): Promise<THREE.Texture> {
  return new Promise((resolve, reject) => {
    loader.load(
      url,
      (t) => {
        t.wrapS = t.wrapT = THREE.RepeatWrapping;
        t.colorSpace = srgb ? THREE.SRGBColorSpace : THREE.NoColorSpace;
        t.anisotropy = 8;
        t.generateMipmaps = true;
        t.minFilter = THREE.LinearMipmapLinearFilter;
        resolve(t);
      },
      undefined,
      () => reject(new Error(`texture ${url}`)),
    );
  });
}

function solid(hex: string, srgb: boolean) {
  const c = new THREE.Color(hex);
  if (srgb) c.convertLinearToSRGB();
  const t = new THREE.DataTexture(
    new Uint8Array([Math.round(c.r * 255), Math.round(c.g * 255), Math.round(c.b * 255), 255]),
    1,
    1,
  );
  t.colorSpace = srgb ? THREE.SRGBColorSpace : THREE.NoColorSpace;
  t.needsUpdate = true;
  return t;
}

export async function loadSurface(kind: SurfaceKind): Promise<SurfaceTextures> {
  const s = SURFACES[kind];
  const base = `${import.meta.env.BASE_URL}textures/${kind}`;
  let map: THREE.Texture, normal: THREE.Texture, rough: THREE.Texture;
  try {
    [map, normal, rough] = await Promise.all([load(`${base}-albedo.jpg`, true), load(`${base}-normal.jpg`, false), load(`${base}-rough.jpg`, false)]);
  } catch {
    // Missing texture set: keep the experience usable with a flat surface
    map = solid(s.fallback, true);
    normal = solid('#8080ff', false);
    rough = solid('#808080', false);
  }
  return {
    map,
    normal,
    rough,
    tileSize: s.tileSize,
    normalStrength: s.normalStrength,
    roughMin: s.roughMin,
    roughMax: s.roughMax,
    tint: s.tint,
    dispose() {
      map.dispose();
      normal.dispose();
      rough.dispose();
    },
  };
}
